# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`methods-import`
	:runtime-requirement    [ :on "perl 5.008006"^^:CpanId ];
	:runtime-requirement    [ :on "Sub::Util"^^:CpanId ];
	:runtime-requirement    [ :on "namespace::clean"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
	:test-requirement       [ :on "Test::Fatal"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.
